module.exports = {
    css: ['./dist/MeirMarchovich/browser/*.css'],
    content: [
        './dist/MeirMarchovich/browser/index.html',
        './dist/MeirMarchovich/browser/*.js',
    ],
    safelist: {
        standard: [
            /^p-/,
            /^p-icon/,
            /^grid/,
            /^col-/,
            /^sm:/,
            /^md:/,
            /^lg:/,
            /^xl:/,
            /^flex/,
            /^gap-/,
            /^justify-/,
            /^align-/,
            /^surface-/,
            /^border-/,
            /^opacity-/,
            /^relative/,
            /^mx-/,
            /^mt-/,
            /^pt-/,
            /^pb-/,
            /^mr-/,
        ],
        greedy: [/p-organizationchart/],
    },
    output: './dist/MeirMarchovich/browser/',
}
